stages:
  - build
  - upload
  - deploy

include:
  - component: $CI_SERVER_FQDN/infrastructure/cdk-deployment-base/python-lambda-build@1.2.1
  - component: $CI_SERVER_FQDN/infrastructure/cdk-deployment-base/python-lambda-upload@1.2.1

deploy:
  stage: deploy
  trigger:
    project: utility-website/cdk
    branch: main
    strategy: depend
  only:
    - main
